import Head from "next/head";
import Banner from "@/components/home/banner";
import Header from "@/components/home/header";

export default function Home() {
  return (
    <>
      <Head>
        <title>spawp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header/>
        <Banner/>
      </main>
    </>
  );
}
